# Generated by Django 4.2.13 on 2024-06-16 08:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='portfolio_images',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to='portfolio_images/'),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to='profile_photos/'),
        ),
    ]
