# Generated by Django 4.2.13 on 2024-06-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_remove_seekerprofile_portfolio_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Profile Photo'),
        ),
    ]
